server:
  port: 0

spring:
  application:
    name: review-service
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

logging:
  level:
    org.hibernate.SQL: DEBUG