spring:
  application:
    name: server

server:
  port: 19090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    hostname: localhost

  server:
    evictableCacheSize: 1000

logging:
  level:
    com.netflex.erueka: WARN
