server:
  port: 19093

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msa_practice
    username: root
    password: ewqDSA19@&
  jpa:
    hibernate:
      ddl-auto: create